// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @notice Interface for zero-knowledge proof verification
 * @dev This interface defines the standard methods for verifying ZK proofs
 *      generated by the Gnark prover. The actual implementation will be
 *      auto-generated by Gnark from the circuit definition.
 *
 * @custom:security This interface is part of the core security infrastructure.
 *                  All implementations must be thoroughly audited before deployment.
 */
interface IVerifier {
    /**
     * @notice Verifies a zero-knowledge proof for a batch of transactions
     * @dev This function verifies a Groth16 proof that a batch of transactions
     *      was correctly executed, resulting in a state transition from
     *      oldStateRoot to newStateRoot.
     *
     * @param a The first part of the proof (G1 point)
     * @param b The second part of the proof (G2 point, represented as [2][2] array)
     * @param c The third part of the proof (G1 point)
     * @param publicInputs The public inputs to the proof:
     *        - publicInputs[0]: oldStateRoot (bytes32)
     *        - publicInputs[1]: newStateRoot (bytes32)
     *        - publicInputs[2]: batchNumber (uint256)
     *        - publicInputs[n]: there may be more inputs, as circuit is not prepared so writing only the valid once for now
     *
     * @return success True if the proof is valid, false otherwise
     *
     * @custom:gas-optimization Target gas cost: < 500k gas
     */
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[3] calldata publicInputs // note: length of inputs will be more, so we are not writing all the inputs for now, it will be decided later as per circuit
    ) external view returns (bool success);

    /**
     * @notice Verifies a batch proof with additional metadata
     * @dev This is an extended verification function that may include additional
     *      validation logic beyond basic proof verification. Useful for
     *      batch-specific checks.
     *
     * @param a The first part of the proof (G1 point)
     * @param b The second part of the proof (G2 point)
     * @param c The third part of the proof (G1 point)
     * @param publicInputs The public inputs to the proof
     * @param batchHash The hash of the batch being verified
     * @param timestamp The timestamp when the batch was created
     *
     * @return success True if the proof and metadata are valid
     */
    function verifyBatchProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[3] calldata publicInputs,
        bytes32 batchHash,
        uint256 timestamp
    ) external view returns (bool success);

    /**
     * @notice Returns the verification key hash
     * @dev This can be used to verify that the correct verifier contract
     *      is being used. The hash should match the expected verification key.
     *
     * @return vkHash The keccak256 hash of the verification key parameters
     */
    function getVerificationKeyHash() external pure returns (bytes32 vkHash);

    /**
     * @notice Returns the circuit size (number of constraints)
     * @dev This is useful for gas estimation and circuit validation
     *
     * @return circuitSize The number of constraints in the circuit
     */
    function getCircuitSize() external pure returns (uint256 circuitSize);

    /**
     * @notice Returns the maximum batch size supported by this verifier
     * @dev Different verifiers may support different batch sizes
     *
     * @return maxBatchSize The maximum number of transactions per batch
     */
    function getMaxBatchSize() external pure returns (uint256 maxBatchSize);
}

