// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @notice Interface for zero-knowledge proof verification
 * @dev This interface defines the standard methods for verifying ZK proofs
 *      generated by the Gnark prover. The actual implementation will be
 *      auto-generated by Gnark from the circuit definition.
 *
 * @custom:security This interface is part of the core security infrastructure.
 *                  All implementations must be thoroughly audited before deployment.
 */
interface IVerifier {
    /**
     * @notice Verifies a Groth16 proof with public inputs
     * @param proofA First component of the proof (G1 point)
     * @param proofB Second component of the proof (G2 point)
     * @param proofC Third component of the proof (G1 point)
     * @param publicInputs Array of public inputs [BatchRoot, PrevStateRoot, NewStateRoot, BatchNumber, Timestamp, SequencerAddr]
     * @return valid True if the proof is valid, false otherwise
     */
    function verifyProof(
        uint256[2] calldata proofA,
        uint256[2][2] calldata proofB,
        uint256[2] calldata proofC,
        uint256[6] calldata publicInputs
    ) external view returns (bool valid);

    /**
     * @notice Returns the verification key hash
     * @dev This can be used to verify that the correct verifier contract
     *      is being used. The hash should match the expected verification key.
     *
     * @return vkHash The keccak256 hash of the verification key parameters
     */
    function getVerificationKeyHash() external pure returns (bytes32 vkHash);

    /**
     * @notice Returns the circuit size (number of constraints)
     * @dev This is useful for gas estimation and circuit validation
     *
     * @return circuitSize The number of constraints in the circuit
     */
    function getCircuitSize() external pure returns (uint256 circuitSize);

    /**
     * @notice Returns the maximum batch size supported by this verifier
     * @dev Different verifiers may support different batch sizes
     *
     * @return maxBatchSize The maximum number of transactions per batch
     */
    function getMaxBatchSize() external pure returns (uint256 maxBatchSize);
}
