// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @notice Interface for zero-knowledge proof verification
 * @dev This interface defines the standard methods for verifying ZK proofs
 *      generated by the Gnark prover. The actual implementation will be
 *      auto-generated by Gnark from the circuit definition.
 *
 * @custom:security This interface is part of the core security infrastructure.
 *                  All implementations must be thoroughly audited before deployment.
 */
interface IVerifier {
    /**
     * @notice Verifies a zero-knowledge proof for a batch of transactions
     * @dev This function verifies a Groth16 proof that a batch of transactions
     *      was correctly executed, resulting in a state transition from
     *      oldStateRoot to newStateRoot.
     *
     * @param a The first part of the proof (G1 point)
     * @param b The second part of the proof (G2 point, represented as [2][2] array)
     * @param c The third part of the proof (G1 point)
     * @param publicInputs The public inputs to the proof:
     *        - publicInputs[0]: oldStateRoot (bytes32 as uint256)
     *        - publicInputs[1]: newStateRoot (bytes32 as uint256)
     *        - publicInputs[2]: batchNumber (uint256)
     *
     * @return success True if the proof is valid, false otherwise
     *
     * @custom:gas-optimization Target gas cost: < 500k gas
     * @custom:note The actual implementation will be generated by Gnark.
     *              The publicInputs array size may change based on circuit requirements.
     */
    function verifyProof(
        uint256[2] calldata a,
        uint256[2][2] calldata b,
        uint256[2] calldata c,
        uint256[4] calldata publicInputs
    ) external view returns (bool success);

    /**
     * @notice Returns the verification key hash
     * @dev This can be used to verify that the correct verifier contract
     *      is being used. The hash should match the expected verification key.
     *
     * @return vkHash The keccak256 hash of the verification key parameters
     */
    function getVerificationKeyHash() external pure returns (bytes32 vkHash);

    /**
     * @notice Returns the circuit size (number of constraints)
     * @dev This is useful for gas estimation and circuit validation
     *
     * @return circuitSize The number of constraints in the circuit
     */
    function getCircuitSize() external pure returns (uint256 circuitSize);

    /**
     * @notice Returns the maximum batch size supported by this verifier
     * @dev Different verifiers may support different batch sizes
     *
     * @return maxBatchSize The maximum number of transactions per batch
     */
    function getMaxBatchSize() external pure returns (uint256 maxBatchSize);
}
