services:

  # --- Indexer Service ---
  indexer:
    build: .
    container_name: nowa-zk-indexer
    command: indexer start --state-db-path /app/data/state
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - API_PORT=8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dir_data/indexer:/app/data
      - ./.nowa-zk:/app/.nowa-zk
    networks:
      - nowa-zk-net
    restart: on-failure

  # --- Prover Service ---
  prover:
    build: .
    container_name: nowa-zk-prover
    command: prover start --indexer-url http://indexer:8080 --keys-dir /app/.nowa-zk/keys
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount generated keys & deployments from host to container
      - ./.nowa-zk:/app/.nowa-zk
    networks:
      - nowa-zk-net
    restart: on-failure

networks:
  nowa-zk-net:
    driver: bridge
