services:

  # --- Sequencer Service ---
  sequencer:
    build: .
    container_name: tan-zk-sequencer
    command: sequencer start --state-db-path /app/data/state
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - API_PORT=8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./dir_data/sequencer:/app/data
      - ./.tan-zk:/app/.tan-zk
    networks:
      - tan-zk-net
    restart: on-failure

  # --- Prover Service ---
  prover:
    build: .
    container_name: tan-zk-prover
    command: prover start --sequencer-url http://sequencer:8080 --keys-dir /app/.tan-zk/keys
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount generated keys & deployments from host to container
      - ./.tan-zk:/app/.tan-zk
    networks:
      - tan-zk-net
    restart: on-failure

networks:
  tan-zk-net:
    driver: bridge
