// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Redirects to Swagger UI",
                "tags": [
                    "Meta"
                ],
                "summary": "List available endpoints",
                "responses": {
                    "302": {
                        "description": "Found"
                    }
                }
            }
        },
        "/batches": {
            "get": {
                "description": "Retrieve multiple batch metadata entries with pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Batches"
                ],
                "summary": "Get batches with pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number (default: 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page - 10, 25, 50, or 100 (default: 25)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paginated batch list",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid parameters",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/batches/latest": {
            "get": {
                "description": "Get details of the latest verified batch from the contract",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Batches"
                ],
                "summary": "Get latest verified batch",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.BatchResponse"
                        }
                    },
                    "404": {
                        "description": "No batches found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/batches/{id}": {
            "get": {
                "description": "Get details of a specific batch",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Batches"
                ],
                "summary": "Get batch by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Batch ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.BatchResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid batch ID",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/status/{id}": {
            "get": {
                "description": "Get proof generation status for a batch",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Proofs"
                ],
                "summary": "Get proof status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Batch ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.StatusResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid batch ID",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal_api.BatchResponse": {
            "type": "object",
            "properties": {
                "batchHash": {
                    "type": "string"
                },
                "batchNumber": {
                    "type": "integer"
                },
                "newStateRoot": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "submitter": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                },
                "txHash": {
                    "type": "string"
                },
                "txHashes": {
                    "description": "L2 transaction hashes",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_api.StatusResponse": {
            "type": "object",
            "properties": {
                "batch_number": {
                    "type": "integer"
                },
                "note": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tan-ZK Prover API",
	Description:      "API for the Tan-ZK Rollup Prover",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
