name: Contracts CI

on:
  push:
    paths:
      - "contracts/**"
      - ".github/workflows/contracts.yml"
  pull_request:
    paths:
      - "contracts/**"
      - ".github/workflows/contracts.yml"

concurrency:
  group: contracts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: contracts

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false

      # Setup Foundry (forge & cast)
      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Show Forge version
        run: forge --version

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.10"
          cache-dependency-path: prover/go.sum

      - name: Generate Verifier
        run: cd .. && make setup

      - name: Install Forge dependencies
        run: forge install foundry-rs/forge-std

      - name: Run Forge fmt
        run: forge fmt --check

      - name: Build contracts
        run: forge build --sizes

      - name: Run tests
        run: forge test -vvv
